# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2
import session_pb2 as session__pb2
import task_pb2 as task__pb2
import artmsg_pb2 as artmsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='imandrax.api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x0cimandrax.api\x1a\x0b\x65rror.proto\x1a\rsession.proto\x1a\ntask.proto\x1a\x0c\x61rtmsg.proto\"G\n\x0b\x43odeSnippet\x12*\n\x07session\x18\x01 \x01(\x0b\x32\x19.imandrax.session.Session\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\x80\x01\n\x15\x43odeSnippetEvalResult\x12%\n\x03res\x18\x01 \x01(\x0e\x32\x18.imandrax.api.EvalResult\x12\x12\n\nduration_s\x18\x03 \x01(\x02\x12\x14\n\x05tasks\x18\t \x03(\x0b\x32\x05.Task\x12\x16\n\x06\x65rrors\x18\n \x03(\x0b\x32\x06.Error\"\x1a\n\nParseQuery\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"-\n\x11\x41rtifactListQuery\x12\x18\n\x07task_id\x18\x01 \x01(\x0b\x32\x07.TaskID\"#\n\x12\x41rtifactListResult\x12\r\n\x05kinds\x18\x01 \x03(\t\":\n\x10\x41rtifactGetQuery\x12\x18\n\x07task_id\x18\x01 \x01(\x0b\x32\x07.TaskID\x12\x0c\n\x04kind\x18\x02 \x01(\t\"\x1d\n\x08\x41rtifact\x12\x11\n\x03\x61rt\x18\x01 \x01(\x0b\x32\x04.Art\"\x1e\n\x0b\x41rtifactZip\x12\x0f\n\x07\x61rt_zip\x18\x01 \x01(\x0c**\n\nEvalResult\x12\x0b\n\x07\x45VAL_OK\x10\x00\x12\x0f\n\x0b\x45VAL_ERRORS\x10\x01\x32\xc9\x03\n\x04\x45val\x12S\n\x11\x65val_code_snippet\x12\x19.imandrax.api.CodeSnippet\x1a#.imandrax.api.CodeSnippetEvalResult\x12?\n\nparse_term\x12\x19.imandrax.api.CodeSnippet\x1a\x16.imandrax.api.Artifact\x12?\n\nparse_type\x12\x19.imandrax.api.CodeSnippet\x1a\x16.imandrax.api.Artifact\x12S\n\x0elist_artifacts\x12\x1f.imandrax.api.ArtifactListQuery\x1a .imandrax.api.ArtifactListResult\x12\x46\n\x0cget_artifact\x12\x1e.imandrax.api.ArtifactGetQuery\x1a\x16.imandrax.api.Artifact\x12M\n\x10get_artifact_zip\x12\x1e.imandrax.api.ArtifactGetQuery\x1a\x19.imandrax.api.ArtifactZipb\x06proto3'
  ,
  dependencies=[error__pb2.DESCRIPTOR,session__pb2.DESCRIPTOR,task__pb2.DESCRIPTOR,artmsg__pb2.DESCRIPTOR,])

_EVALRESULT = _descriptor.EnumDescriptor(
  name='EvalResult',
  full_name='imandrax.api.EvalResult',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVAL_OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVAL_ERRORS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=520,
  serialized_end=562,
)
_sym_db.RegisterEnumDescriptor(_EVALRESULT)

EvalResult = enum_type_wrapper.EnumTypeWrapper(_EVALRESULT)
EVAL_OK = 0
EVAL_ERRORS = 1



_CODESNIPPET = _descriptor.Descriptor(
  name='CodeSnippet',
  full_name='imandrax.api.CodeSnippet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='imandrax.api.CodeSnippet.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='imandrax.api.CodeSnippet.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=152,
)


_CODESNIPPETEVALRESULT = _descriptor.Descriptor(
  name='CodeSnippetEvalResult',
  full_name='imandrax.api.CodeSnippetEvalResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='imandrax.api.CodeSnippetEvalResult.res', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_s', full_name='imandrax.api.CodeSnippetEvalResult.duration_s', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tasks', full_name='imandrax.api.CodeSnippetEvalResult.tasks', index=2,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errors', full_name='imandrax.api.CodeSnippetEvalResult.errors', index=3,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=283,
)


_PARSEQUERY = _descriptor.Descriptor(
  name='ParseQuery',
  full_name='imandrax.api.ParseQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='imandrax.api.ParseQuery.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=311,
)


_ARTIFACTLISTQUERY = _descriptor.Descriptor(
  name='ArtifactListQuery',
  full_name='imandrax.api.ArtifactListQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='imandrax.api.ArtifactListQuery.task_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=358,
)


_ARTIFACTLISTRESULT = _descriptor.Descriptor(
  name='ArtifactListResult',
  full_name='imandrax.api.ArtifactListResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kinds', full_name='imandrax.api.ArtifactListResult.kinds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=395,
)


_ARTIFACTGETQUERY = _descriptor.Descriptor(
  name='ArtifactGetQuery',
  full_name='imandrax.api.ArtifactGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='imandrax.api.ArtifactGetQuery.task_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kind', full_name='imandrax.api.ArtifactGetQuery.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=455,
)


_ARTIFACT = _descriptor.Descriptor(
  name='Artifact',
  full_name='imandrax.api.Artifact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='art', full_name='imandrax.api.Artifact.art', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=486,
)


_ARTIFACTZIP = _descriptor.Descriptor(
  name='ArtifactZip',
  full_name='imandrax.api.ArtifactZip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='art_zip', full_name='imandrax.api.ArtifactZip.art_zip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=518,
)

_CODESNIPPET.fields_by_name['session'].message_type = session__pb2._SESSION
_CODESNIPPETEVALRESULT.fields_by_name['res'].enum_type = _EVALRESULT
_CODESNIPPETEVALRESULT.fields_by_name['tasks'].message_type = task__pb2._TASK
_CODESNIPPETEVALRESULT.fields_by_name['errors'].message_type = error__pb2._ERROR
_ARTIFACTLISTQUERY.fields_by_name['task_id'].message_type = task__pb2._TASKID
_ARTIFACTGETQUERY.fields_by_name['task_id'].message_type = task__pb2._TASKID
_ARTIFACT.fields_by_name['art'].message_type = artmsg__pb2._ART
DESCRIPTOR.message_types_by_name['CodeSnippet'] = _CODESNIPPET
DESCRIPTOR.message_types_by_name['CodeSnippetEvalResult'] = _CODESNIPPETEVALRESULT
DESCRIPTOR.message_types_by_name['ParseQuery'] = _PARSEQUERY
DESCRIPTOR.message_types_by_name['ArtifactListQuery'] = _ARTIFACTLISTQUERY
DESCRIPTOR.message_types_by_name['ArtifactListResult'] = _ARTIFACTLISTRESULT
DESCRIPTOR.message_types_by_name['ArtifactGetQuery'] = _ARTIFACTGETQUERY
DESCRIPTOR.message_types_by_name['Artifact'] = _ARTIFACT
DESCRIPTOR.message_types_by_name['ArtifactZip'] = _ARTIFACTZIP
DESCRIPTOR.enum_types_by_name['EvalResult'] = _EVALRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CodeSnippet = _reflection.GeneratedProtocolMessageType('CodeSnippet', (_message.Message,), {
  'DESCRIPTOR' : _CODESNIPPET,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.CodeSnippet)
  })
_sym_db.RegisterMessage(CodeSnippet)

CodeSnippetEvalResult = _reflection.GeneratedProtocolMessageType('CodeSnippetEvalResult', (_message.Message,), {
  'DESCRIPTOR' : _CODESNIPPETEVALRESULT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.CodeSnippetEvalResult)
  })
_sym_db.RegisterMessage(CodeSnippetEvalResult)

ParseQuery = _reflection.GeneratedProtocolMessageType('ParseQuery', (_message.Message,), {
  'DESCRIPTOR' : _PARSEQUERY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.ParseQuery)
  })
_sym_db.RegisterMessage(ParseQuery)

ArtifactListQuery = _reflection.GeneratedProtocolMessageType('ArtifactListQuery', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTLISTQUERY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.ArtifactListQuery)
  })
_sym_db.RegisterMessage(ArtifactListQuery)

ArtifactListResult = _reflection.GeneratedProtocolMessageType('ArtifactListResult', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTLISTRESULT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.ArtifactListResult)
  })
_sym_db.RegisterMessage(ArtifactListResult)

ArtifactGetQuery = _reflection.GeneratedProtocolMessageType('ArtifactGetQuery', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTGETQUERY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.ArtifactGetQuery)
  })
_sym_db.RegisterMessage(ArtifactGetQuery)

Artifact = _reflection.GeneratedProtocolMessageType('Artifact', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.Artifact)
  })
_sym_db.RegisterMessage(Artifact)

ArtifactZip = _reflection.GeneratedProtocolMessageType('ArtifactZip', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTZIP,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.api.ArtifactZip)
  })
_sym_db.RegisterMessage(ArtifactZip)



_EVAL = _descriptor.ServiceDescriptor(
  name='Eval',
  full_name='imandrax.api.Eval',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=565,
  serialized_end=1022,
  methods=[
  _descriptor.MethodDescriptor(
    name='eval_code_snippet',
    full_name='imandrax.api.Eval.eval_code_snippet',
    index=0,
    containing_service=None,
    input_type=_CODESNIPPET,
    output_type=_CODESNIPPETEVALRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='parse_term',
    full_name='imandrax.api.Eval.parse_term',
    index=1,
    containing_service=None,
    input_type=_CODESNIPPET,
    output_type=_ARTIFACT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='parse_type',
    full_name='imandrax.api.Eval.parse_type',
    index=2,
    containing_service=None,
    input_type=_CODESNIPPET,
    output_type=_ARTIFACT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='list_artifacts',
    full_name='imandrax.api.Eval.list_artifacts',
    index=3,
    containing_service=None,
    input_type=_ARTIFACTLISTQUERY,
    output_type=_ARTIFACTLISTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_artifact',
    full_name='imandrax.api.Eval.get_artifact',
    index=4,
    containing_service=None,
    input_type=_ARTIFACTGETQUERY,
    output_type=_ARTIFACT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_artifact_zip',
    full_name='imandrax.api.Eval.get_artifact_zip',
    index=5,
    containing_service=None,
    input_type=_ARTIFACTGETQUERY,
    output_type=_ARTIFACTZIP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVAL)

DESCRIPTOR.services_by_name['Eval'] = _EVAL

# @@protoc_insertion_point(module_scope)
