# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import locs_pb2 as locs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='error.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65rror.proto\x1a\nlocs.proto\"\xca\x01\n\x05\x45rror\x12\x1b\n\x03msg\x18\x01 \x01(\x0b\x32\x0e.Error.Message\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x1d\n\x05stack\x18\x03 \x03(\x0b\x32\x0e.Error.Message\x12\x14\n\x07process\x18\x04 \x01(\tH\x00\x88\x01\x01\x1aU\n\x07Message\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x17\n\x04locs\x18\x02 \x03(\x0b\x32\t.Location\x12\x16\n\tbacktrace\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_backtraceB\n\n\x08_processb\x06proto3'
  ,
  dependencies=[locs__pb2.DESCRIPTOR,])




_ERROR_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Error.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Error.Message.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locs', full_name='Error.Message.locs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backtrace', full_name='Error.Message.backtrace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_backtrace', full_name='Error.Message._backtrace',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=133,
  serialized_end=218,
)

_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Error.msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kind', full_name='Error.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stack', full_name='Error.stack', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='process', full_name='Error.process', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ERROR_MESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_process', full_name='Error._process',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=28,
  serialized_end=230,
)

_ERROR_MESSAGE.fields_by_name['locs'].message_type = locs__pb2._LOCATION
_ERROR_MESSAGE.containing_type = _ERROR
_ERROR_MESSAGE.oneofs_by_name['_backtrace'].fields.append(
  _ERROR_MESSAGE.fields_by_name['backtrace'])
_ERROR_MESSAGE.fields_by_name['backtrace'].containing_oneof = _ERROR_MESSAGE.oneofs_by_name['_backtrace']
_ERROR.fields_by_name['msg'].message_type = _ERROR_MESSAGE
_ERROR.fields_by_name['stack'].message_type = _ERROR_MESSAGE
_ERROR.oneofs_by_name['_process'].fields.append(
  _ERROR.fields_by_name['process'])
_ERROR.fields_by_name['process'].containing_oneof = _ERROR.oneofs_by_name['_process']
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {

  'Message' : _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR' : _ERROR_MESSAGE,
    '__module__' : 'error_pb2'
    # @@protoc_insertion_point(class_scope:Error.Message)
    })
  ,
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:Error)
  })
_sym_db.RegisterMessage(Error)
_sym_db.RegisterMessage(Error.Message)


# @@protoc_insertion_point(module_scope)
