# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: locs.proto

from google.protobuf import symbol_database as _symbol_database

from ..twirp.async_client import AsyncTwirpClient

_sym_db = _symbol_database.Default()
