# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='session.proto',
  package='imandrax.session',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsession.proto\x12\x10imandrax.session\x1a\x0butils.proto\"\x15\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\t\"H\n\rSessionCreate\x12\x15\n\x08po_check\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x13\n\x0b\x61pi_version\x18\x02 \x01(\tB\x0b\n\t_po_check\"I\n\x0bSessionOpen\x12%\n\x02id\x18\x01 \x01(\x0b\x32\x19.imandrax.session.Session\x12\x13\n\x0b\x61pi_version\x18\x02 \x01(\t2\xce\x01\n\x0eSessionManager\x12L\n\x0e\x63reate_session\x12\x1f.imandrax.session.SessionCreate\x1a\x19.imandrax.session.Session\x12\x35\n\x0copen_session\x12\x1d.imandrax.session.SessionOpen\x1a\x06.Empty\x12\x37\n\x12keep_session_alive\x12\x19.imandrax.session.Session\x1a\x06.Emptyb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])




_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='imandrax.session.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='imandrax.session.Session.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=69,
)


_SESSIONCREATE = _descriptor.Descriptor(
  name='SessionCreate',
  full_name='imandrax.session.SessionCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='po_check', full_name='imandrax.session.SessionCreate.po_check', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='imandrax.session.SessionCreate.api_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_po_check', full_name='imandrax.session.SessionCreate._po_check',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=71,
  serialized_end=143,
)


_SESSIONOPEN = _descriptor.Descriptor(
  name='SessionOpen',
  full_name='imandrax.session.SessionOpen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='imandrax.session.SessionOpen.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='imandrax.session.SessionOpen.api_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=218,
)

_SESSIONCREATE.oneofs_by_name['_po_check'].fields.append(
  _SESSIONCREATE.fields_by_name['po_check'])
_SESSIONCREATE.fields_by_name['po_check'].containing_oneof = _SESSIONCREATE.oneofs_by_name['_po_check']
_SESSIONOPEN.fields_by_name['id'].message_type = _SESSION
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['SessionCreate'] = _SESSIONCREATE
DESCRIPTOR.message_types_by_name['SessionOpen'] = _SESSIONOPEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'session_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.session.Session)
  })
_sym_db.RegisterMessage(Session)

SessionCreate = _reflection.GeneratedProtocolMessageType('SessionCreate', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONCREATE,
  '__module__' : 'session_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.session.SessionCreate)
  })
_sym_db.RegisterMessage(SessionCreate)

SessionOpen = _reflection.GeneratedProtocolMessageType('SessionOpen', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONOPEN,
  '__module__' : 'session_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.session.SessionOpen)
  })
_sym_db.RegisterMessage(SessionOpen)



_SESSIONMANAGER = _descriptor.ServiceDescriptor(
  name='SessionManager',
  full_name='imandrax.session.SessionManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=221,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_session',
    full_name='imandrax.session.SessionManager.create_session',
    index=0,
    containing_service=None,
    input_type=_SESSIONCREATE,
    output_type=_SESSION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='open_session',
    full_name='imandrax.session.SessionManager.open_session',
    index=1,
    containing_service=None,
    input_type=_SESSIONOPEN,
    output_type=utils__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='keep_session_alive',
    full_name='imandrax.session.SessionManager.keep_session_alive',
    index=2,
    containing_service=None,
    input_type=_SESSION,
    output_type=utils__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONMANAGER)

DESCRIPTOR.services_by_name['SessionManager'] = _SESSIONMANAGER

# @@protoc_insertion_point(module_scope)
