# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system.proto',
  package='imandrax.system',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csystem.proto\x12\x0fimandrax.system\x1a\x0butils.proto\"U\n\x08Gc_stats\x12\x13\n\x0bheap_size_B\x18\x01 \x01(\x03\x12\x19\n\x11major_collections\x18\x02 \x01(\x03\x12\x19\n\x11minor_collections\x18\x03 \x01(\x03\"L\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x18\n\x0bgit_version\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_git_version2\xa1\x01\n\x06System\x12\x33\n\x07version\x12\x06.Empty\x1a .imandrax.system.VersionResponse\x12-\n\x08gc_stats\x12\x06.Empty\x1a\x19.imandrax.system.Gc_stats\x12\x33\n\x0erelease_memory\x12\x06.Empty\x1a\x19.imandrax.system.Gc_statsb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])




_GC_STATS = _descriptor.Descriptor(
  name='Gc_stats',
  full_name='imandrax.system.Gc_stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='heap_size_B', full_name='imandrax.system.Gc_stats.heap_size_B', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='major_collections', full_name='imandrax.system.Gc_stats.major_collections', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minor_collections', full_name='imandrax.system.Gc_stats.minor_collections', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=131,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='imandrax.system.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='imandrax.system.VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='git_version', full_name='imandrax.system.VersionResponse.git_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_git_version', full_name='imandrax.system.VersionResponse._git_version',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=133,
  serialized_end=209,
)

_VERSIONRESPONSE.oneofs_by_name['_git_version'].fields.append(
  _VERSIONRESPONSE.fields_by_name['git_version'])
_VERSIONRESPONSE.fields_by_name['git_version'].containing_oneof = _VERSIONRESPONSE.oneofs_by_name['_git_version']
DESCRIPTOR.message_types_by_name['Gc_stats'] = _GC_STATS
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gc_stats = _reflection.GeneratedProtocolMessageType('Gc_stats', (_message.Message,), {
  'DESCRIPTOR' : _GC_STATS,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.system.Gc_stats)
  })
_sym_db.RegisterMessage(Gc_stats)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:imandrax.system.VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)



_SYSTEM = _descriptor.ServiceDescriptor(
  name='System',
  full_name='imandrax.system.System',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=212,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='version',
    full_name='imandrax.system.System.version',
    index=0,
    containing_service=None,
    input_type=utils__pb2._EMPTY,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='gc_stats',
    full_name='imandrax.system.System.gc_stats',
    index=1,
    containing_service=None,
    input_type=utils__pb2._EMPTY,
    output_type=_GC_STATS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='release_memory',
    full_name='imandrax.system.System.release_memory',
    index=2,
    containing_service=None,
    input_type=utils__pb2._EMPTY,
    output_type=_GC_STATS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEM)

DESCRIPTOR.services_by_name['System'] = _SYSTEM

# @@protoc_insertion_point(module_scope)
