# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: system.proto

from google.protobuf import symbol_database as _symbol_database

from ..twirp.async_client import AsyncTwirpClient

_sym_db = _symbol_database.Default()


class AsyncSystemClient(AsyncTwirpClient):

	async def version(self, *, ctx, request, **kwargs):
		return await self._make_request(
			url=F"{self._server_path_prefix}/imandrax.system.System/version",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("imandrax.system.VersionResponse"),
			**kwargs,
		)

	async def gc_stats(self, *, ctx, request, **kwargs):
		return await self._make_request(
			url=F"{self._server_path_prefix}/imandrax.system.System/gc_stats",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("imandrax.system.Gc_stats"),
			**kwargs,
		)

	async def release_memory(self, *, ctx, request, **kwargs):
		return await self._make_request(
			url=F"{self._server_path_prefix}/imandrax.system.System/release_memory",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("imandrax.system.Gc_stats"),
			**kwargs,
		)
