# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntask.proto\"\x14\n\x06TaskID\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x04Task\x12\x13\n\x02id\x18\x01 \x01(\x0b\x32\x07.TaskID\x12\x17\n\x04kind\x18\x02 \x01(\x0e\x32\t.TaskKind*i\n\x08TaskKind\x12\x14\n\x10TASK_UNSPECIFIED\x10\x00\x12\r\n\tTASK_EVAL\x10\x01\x12\x11\n\rTASK_CHECK_PO\x10\x02\x12\x14\n\x10TASK_PROOF_CHECK\x10\x03\x12\x0f\n\x0bTASK_DECOMP\x10\x04\x62\x06proto3'
)

_TASKKIND = _descriptor.EnumDescriptor(
  name='TaskKind',
  full_name='TaskKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_EVAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_CHECK_PO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_PROOF_CHECK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_DECOMP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=90,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_TASKKIND)

TaskKind = enum_type_wrapper.EnumTypeWrapper(_TASKKIND)
TASK_UNSPECIFIED = 0
TASK_EVAL = 1
TASK_CHECK_PO = 2
TASK_PROOF_CHECK = 3
TASK_DECOMP = 4



_TASKID = _descriptor.Descriptor(
  name='TaskID',
  full_name='TaskID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=34,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Task.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kind', full_name='Task.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=88,
)

_TASK.fields_by_name['id'].message_type = _TASKID
_TASK.fields_by_name['kind'].enum_type = _TASKKIND
DESCRIPTOR.message_types_by_name['TaskID'] = _TASKID
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.enum_types_by_name['TaskKind'] = _TASKKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskID = _reflection.GeneratedProtocolMessageType('TaskID', (_message.Message,), {
  'DESCRIPTOR' : _TASKID,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:TaskID)
  })
_sym_db.RegisterMessage(TaskID)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:Task)
  })
_sym_db.RegisterMessage(Task)


# @@protoc_insertion_point(module_scope)
