FROM ocaml/opam:debian-ocaml-5.2 AS base

WORKDIR /build/
RUN cd /home/opam/opam-repository; git fetch origin; git checkout 11bdbee61114a1cfa080b764e71c72a5760a93f0 -q; opam upd
RUN sudo chown -R opam: /build/
COPY --chown=opam ./src/ ./src/
COPY --chown=opam ./vendor ./vendor
COPY --chown=opam \
  imandrax-api.opam \
  imandrax-api-cli.opam  \
  imandrax-api-client.opam  \
  imandra-proof-system.opam \
  imandrax-api-client-ezcurl.opam  \
  imandrax-api-client-cohttp.opam  \
  Makefile dune-project .ocamlformat \
  ./

# for ezcurl
RUN sudo apt install curl libcurl4-gnutls-dev -y

RUN opam depext -yt zarith conf-pkg-config camlzip
RUN opam pin -n .

RUN opam install -t imandrax-api imandrax-api-client \
  imandrax-api-client-ezcurl \
  imandrax-api-client-cohttp imandrax-api-cli \
  --deps-only
RUN opam exec -- dune build @install --ignore-promoted-rules
RUN opam exec -- dune runtest --ignore-promoted-rules

# check that the generated code is up to date
RUN for pkg in pbrt pbrt_yojson ocaml-protoc; do opam pin $pkg --dev -y -n ; done
RUN opam install ocaml-protoc
RUN opam exec -- dune build @genproto --auto-promote
COPY --chown=opam ./.git ./.git
RUN git diff  --quiet src
