FROM ocaml/opam:debian-ocaml-5.2 AS base

WORKDIR /build/
RUN sudo chown -R opam: /build/
COPY --chown=opam ./src/ ./src/
COPY --chown=opam ./vendor ./vendor
COPY --chown=opam \
  imandrax-api.opam \
  imandrax-api-proto.opam \
  imandrax-api-cli.opam  \
  imandrax-api-client.opam  \
  imandrax-api-client-batrpc.opam  \
  imandrax-api-client-ezcurl.opam  \
  Makefile dune-project .ocamlformat \
  ./

RUN opam depext -yt zarith conf-pkg-config camlzip
RUN opam exec -- make opam-pin-submodules-nodep
RUN opam pin -n .

RUN opam install -t imandrax-api imandrax-api-proto imandrax-api-client \
  imandrax-api-client-batrpc imandrax-api-client-ezcurl imandrax-api-cli \
  --deps-only
RUN opam exec -- dune build @install --ignore-promoted-rules
RUN opam exec -- dune runtest --ignore-promoted-rules

# check that the generated code is up to date
RUN opam install ocaml-protoc
RUN opam exec -- dune build @genproto --auto-promote
RUN git diff -q
