FROM ocaml/opam:debian-ocaml-4.14 AS base
WORKDIR /build/
RUN cd /home/opam/opam-repository; git fetch origin; git checkout c80b5ac03487baaaf2f482adf2347e782d0b673c  -q; opam upd
RUN sudo chown -R opam: /build/
COPY --chown=opam ./src/ ./src/
COPY --chown=opam ./vendor ./vendor
COPY --chown=opam \
  imandrax-api.opam  \
  imandra-proof-system.opam \
  imandra-proof-system.opam \
  imandrax-api-client.opam  \
  imandrax-api-client-ezcurl.opam  \
  imandrax-api-client-cohttp.opam  \
  Makefile dune-project .ocamlformat \
  ./

RUN opam depext -yt zarith conf-pkg-config camlzip
RUN opam pin -n .

# Until there's a new release of `trace`, we need to pin it.
RUN opam pin https://github.com/c-cube/ocaml-trace.git -y -n

RUN opam install -t imandrax-api imandrax-api-client imandrax-api-client-cohttp \
  --deps-only
RUN opam exec -- dune build @install -p \
  imandrax-api,imandrax-api-client,imandrax-api-client-cohttp
RUN opam exec -- dune runtest -p \
  imandrax-api,imandrax-api-client,imandrax-api-client-cohttp

# check that the generated code is up to date
RUN for pkg in pbrt pbrt_yojson ocaml-protoc; do opam pin $pkg.4.0 -y -n ; done
RUN opam install ocaml-protoc
RUN opam exec -- dune build @genproto --auto-promote
COPY --chown=opam ./.git ./.git
RUN git diff  --quiet src
