name: format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

      # Commit sha of nixpkgs release-23.11 as of 2024-04-24. Need 23.11 as it still has ocamlformat_0_22_4 available.
    - uses: imandra-ai/imandra-build-config/actions/self-hosted-linux-runner-setup-ssh@46c4c21f5e783fc4b9bc172cf900a5f62ea285bf
    - uses: cachix/install-nix-action@v20
    - id: 'dune-fmt'
      name: 'dune build @fmt'
      run: |-
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/bffc22eb12172e6db3c5dde9e3e5628f8e3e7912.tar.gz  dep/format.nix --command "make check-format DUNE=dune"
