name: Installer smoke-test

on:
  push:
    branches: [main]
  pull_request:

env:
  INSTALL_PREFIX: ${{ github.workspace }}/.test_install

jobs:
  run-macos-installer:
    strategy:
      matrix:
        include:
          - os: macos-latest
            shellcheck-file: shellcheck-v0.10.0.darwin.aarch64.tar.xz
          - os: ubuntu-latest
            shellcheck-file: shellcheck-v0.10.0.linux.x86_64.tar.xz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Alt shellcheck
        run: |
          wget https://github.com/koalaman/shellcheck/releases/download/v0.10.0/${{ matrix.shellcheck-file}}
          tar -xf ${{ matrix.shellcheck-file}}
          shellcheck-v0.10.0/shellcheck scripts/install.sh

      - name: Make script executable
        run: chmod +x scripts/install.sh

      - name: Run installer script
        env:
          INSTALL_PREFIX: ${{ env.INSTALL_PREFIX }}
          VERSION: latest
        run: yes | scripts/install.sh

      - name: Run ImandraX version
        run: ${{ env.INSTALL_PREFIX }}/bin/imandrax-cli version | grep -q '^imandrax'
