name: Installer smoke-test

on:
  push:
    branches: [main]
  pull_request:

env:
  INSTALL_PREFIX: ${{ github.workspace }}/.test_install

jobs:
  run-macos-installer:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/install

      - name: Run installer script
        env:
          INSTALL_PREFIX: ${{ env.INSTALL_PREFIX }}
          VERSION: latest
        run: yes | scripts/install

      - name: Run ImandraX version
        run: "{{ env.INSTALL_PREFIX }}/bin/imandrax-cli version | grep -q '^imandrax'"
