name: build and test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-4-14:
    name: build 4.14
    timeout-minutes: 10
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@main
      - run: docker build . -f dep/Dockerfile.4.14
