name: build and test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-4-14:
    name: build 4.14
    timeout-minutes: 10
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - run: make update-submodules
      - run: docker build . -f dep/Dockerfile.4.14
  run-5-2:
    name: build 5.2
    timeout-minutes: 10
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - run: make update-submodules
      - run: docker build . -f dep/Dockerfile.5.2
  tsc:
    name: tsc
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@main
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: npm install tsc
    - name: tsc
      run: make -C src/ts check
